[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  exclude = ["*/custom/**"]

[".local/share/oh-my-zsh/plugins/evalcache"]
  type = "archive"
  url = "https://github.com/mroth/evalcache/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".local/share/oh-my-zsh/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
